var linear_videos = [
    {   
        "id":"Linear_1",
        "condition":"Linear",
        "number":1,
        "src":"Videos/Linear/Linear_1.mp4"
    },
    {   
        "id":"Linear_2",
        "condition":"Linear",
        "number":2,
        "src":"Videos/Linear/Linear_2.mp4"
    },
    {   
        "id":"Linear_3",
        "condition":"Linear",
        "number":3,
        "src":"Videos/Linear/Linear_3.mp4"
    },
    {   
        "id":"Linear_4",
        "condition":"Linear",
        "number":4,
        "src":"Videos/Linear/Linear_4.mp4"
    },    
    {   
        "id":"Linear_5",
        "condition":"Linear",
        "number":5,
        "src":"Videos/Linear/Linear_5.mp4"
    }]
    var adaptive_videos=[   
    {   
        "id":"Adaptive_1",
        "condition":"Adaptive",
        "number":1,
        "src":"Videos/Adaptive/Adapt_1.mp4"
    },
    {   
        "id":"Adaptive_2",
        "condition":"Adaptive",
        "number":2,
        "src":"Videos/Adaptive/Adapt_2.mp4"
    },
    {   
        "id":"Adaptive_3",
        "condition":"Adaptive",
        "number":3,
        "src":"Videos/Adaptive/Adapt_3.mp4"
    },
    {   
        "id":"Adaptive_4",
        "condition":"Adaptive",
        "number":4,
        "src":"Videos/Adaptive/Adapt_4.mp4"
    },    
    {   
        "id":"Adaptive_5",
        "condition":"Adaptive",
        "number":5,
        "src":"Videos/Adaptive/Adapt_5.mp4"
    }
]
var generative_videos=[
    {   
        "id":"Generative_1",
        "condition":"Generative",
        "number":1,
        "src":"Videos/Generative/Gen_1.mp4"
    },
    {   
        "id":"Generative_2",
        "condition":"Generative",
        "number":2,
        "src":"Videos/Generative/Gen_2.mp4"
    },
    {   
        "id":"Generative_3",
        "condition":"Generative",
        "number":3,
        "src":"Videos/Generative/Gen_3.mp4"
    },
    {   
        "id":"Generative_4",
        "condition":"Generative",
        "number":4,
        "src":"Videos/Generative/Gen_4.mp4"
    },    
    {   
        "id":"Generative_5",
        "condition":"Generative",
        "number":5,
        "src":"Videos/Generative/Gen_5.mp4"
    }
]
var none_videos=[
    {   
        "id":"None_1",
        "condition":"None",
        "number":1,
        "src":"Videos/None/None_1.mp4"
    },
    {   
        "id":"None_2",
        "condition":"None",
        "number":2,
        "src":"Videos/None/None_2.mp4"
    },
    {   
        "id":"None_3",
        "condition":"None",
        "number":3,
        "src":"Videos/None/None_3.mp4"
    },
    {   
        "id":"None_4",
        "condition":"None",
        "number":4,
        "src":"Videos/None/None_4.mp4"
    },    
    {   
        "id":"None_5",
        "condition":"None",
        "number":5,
        "src":"Videos/None/None_5.mp4"
    },
    
]