var linear_videos_valence = [
    {   
        "id":"L_V_1",
        "condition":"Linear",
        "number":1,
        "src":"valence_1_source"
    },
    {   
        "id":"L_V_2",
        "condition":"Linear",
        "number":2,
        "src":"valence_2_source"
    },
    {   
        "id":"L_V_3",
        "condition":"Linear",
        "number":3,
        "src":"valence_3_source"
    },
    {   
        "id":"L_V_4",
        "condition":"Linear",
        "number":4,
        "src":"valence_4_source"
    },    
    {   
        "id":"L_V_5",
        "condition":"Linear",
        "number":5,
        "src":"valence_5_source"
    },
    {   
        "id":"L_V_6",
        "condition":"Linear",
        "number":6,
        "src":"valence_6_source"
    },
    {   
        "id":"L_V_7",
        "condition":"Linear",
        "number":7,
        "src":"valence_7_source"
    },
    {   
        "id":"L_V_8",
        "condition":"Linear",
        "number":8,
        "src":"valence_8_source"
    },
    {   
        "id":"L_V_9",
        "condition":"Linear",
        "number":9,
        "src":"valence_9_source"
    },
    {   
        "id":"L_V_10",
        "condition":"Linear",
        "number":10,
        "src":"valence_10_source"
    }]
    var linear_videos_arousal=[   
    {   
        "id":"L_A_1",
        "condition":"Linear",
        "number":1,
        "src":"arousal_1_source"
    },
    {   
        "id":"L_A_2",
        "condition":"Linear",
        "number":2,
        "src":"arousal_2_source"
    },
    {   
        "id":"L_A_3",
        "condition":"Linear",
        "number":3,
        "src":"arousal_3_source"
    },
    {   
        "id":"L_A_4",
        "condition":"Linear",
        "number":4,
        "src":"arousal_4_source"
    },    
    {   
        "id":"L_A_5",
        "condition":"Linear",
        "number":5,
        "src":"arousal_5_source"
    },
    {   
        "id":"L_A_6",
        "condition":"Linear",
        "number":6,
        "src":"arousal_6_source"
    },
    {   
        "id":"L_A_7",
        "condition":"Linear",
        "number":7,
        "src":"arousal_7_source"
    },
    {   
        "id":"L_A_8",
        "condition":"Linear",
        "number":8,
        "src":"arousal_8_source"
    },
    {   
        "id":"L_A_9",
        "condition":"Linear",
        "number":9,
        "src":"arousal_9_source"
    },
    {   
        "id":"L_A_10",
        "condition":"Linear",
        "number":10,
        "src":"arousal_10_source"
    }
]
var linear_videos_tension=[
    {   
        "id":"L_T_1",
        "condition":"Linear",
        "number":1,
        "src":"tension_1_source"
    },
    {   
        "id":"L_T_2",
        "condition":"Linear",
        "number":2,
        "src":"tension_2_source"
    },
    {   
        "id":"L_T_3",
        "condition":"Linear",
        "number":3,
        "src":"tension_3_source"
    },
    {   
        "id":"L_T_4",
        "condition":"Linear",
        "number":4,
        "src":"tension_4_source"
    },    
    {   
        "id":"L_T_5",
        "condition":"Linear",
        "number":5,
        "src":"tension_5_source"
    },
    {   
        "id":"L_T_6",
        "condition":"Linear",
        "number":6,
        "src":"tension_6_source"
    },
    {   
        "id":"L_T_7",
        "condition":"Linear",
        "number":7,
        "src":"tension_7_source"
    },
    {   
        "id":"L_T_8",
        "condition":"Linear",
        "number":8,
        "src":"tension_8_source"
    },
    {   
        "id":"L_T_9",
        "condition":"Linear",
        "number":9,
        "src":"tension_9_source"
    },
    {   
        "id":"L_T_10",
        "condition":"Linear",
        "number":10,
        "src":"tension_10_source"
    }
]
var adaptive_videos_valence = [
    {   
        "id":"L_V_1",
        "condition":"Adaptive",
        "number":1,
        "src":"valence_1_source"
    },
    {   
        "id":"L_V_2",
        "condition":"Adaptive",
        "number":2,
        "src":"valence_2_source"
    },
    {   
        "id":"L_V_3",
        "condition":"Adaptive",
        "number":3,
        "src":"valence_3_source"
    },
    {   
        "id":"L_V_4",
        "condition":"Adaptive",
        "number":4,
        "src":"valence_4_source"
    },    
    {   
        "id":"L_V_5",
        "condition":"Adaptive",
        "number":5,
        "src":"valence_5_source"
    },
    {   
        "id":"L_V_6",
        "condition":"Adaptive",
        "number":6,
        "src":"valence_6_source"
    },
    {   
        "id":"L_V_7",
        "condition":"Adaptive",
        "number":7,
        "src":"valence_7_source"
    },
    {   
        "id":"L_V_8",
        "condition":"Adaptive",
        "number":8,
        "src":"valence_8_source"
    },
    {   
        "id":"L_V_9",
        "condition":"Adaptive",
        "number":9,
        "src":"valence_9_source"
    },
    {   
        "id":"L_V_10",
        "condition":"Adaptive",
        "number":10,
        "src":"valence_10_source"
    }]
    var adaptive_videos_arousal=[   
    {   
        "id":"L_A_1",
        "condition":"Adaptive",
        "number":1,
        "src":"arousal_1_source"
    },
    {   
        "id":"L_A_2",
        "condition":"Adaptive",
        "number":2,
        "src":"arousal_2_source"
    },
    {   
        "id":"L_A_3",
        "condition":"Adaptive",
        "number":3,
        "src":"arousal_3_source"
    },
    {   
        "id":"L_A_4",
        "condition":"Adaptive",
        "number":4,
        "src":"arousal_4_source"
    },    
    {   
        "id":"L_A_5",
        "condition":"Adaptive",
        "number":5,
        "src":"arousal_5_source"
    },
    {   
        "id":"L_A_6",
        "condition":"Adaptive",
        "number":6,
        "src":"arousal_6_source"
    },
    {   
        "id":"L_A_7",
        "condition":"Adaptive",
        "number":7,
        "src":"arousal_7_source"
    },
    {   
        "id":"L_A_8",
        "condition":"Adaptive",
        "number":8,
        "src":"arousal_8_source"
    },
    {   
        "id":"L_A_9",
        "condition":"Adaptive",
        "number":9,
        "src":"arousal_9_source"
    },
    {   
        "id":"L_A_10",
        "condition":"Adaptive",
        "number":10,
        "src":"arousal_10_source"
    }
]
var adaptive_videos_tension=[
    {   
        "id":"L_T_1",
        "condition":"Adaptive",
        "number":1,
        "src":"tension_1_source"
    },
    {   
        "id":"L_T_2",
        "condition":"Adaptive",
        "number":2,
        "src":"tension_2_source"
    },
    {   
        "id":"L_T_3",
        "condition":"Adaptive",
        "number":3,
        "src":"tension_3_source"
    },
    {   
        "id":"L_T_4",
        "condition":"Adaptive",
        "number":4,
        "src":"tension_4_source"
    },    
    {   
        "id":"L_T_5",
        "condition":"Adaptive",
        "number":5,
        "src":"tension_5_source"
    },
    {   
        "id":"L_T_6",
        "condition":"Adaptive",
        "number":6,
        "src":"tension_6_source"
    },
    {   
        "id":"L_T_7",
        "condition":"Adaptive",
        "number":7,
        "src":"tension_7_source"
    },
    {   
        "id":"L_T_8",
        "condition":"Adaptive",
        "number":8,
        "src":"tension_8_source"
    },
    {   
        "id":"L_T_9",
        "condition":"Adaptive",
        "number":9,
        "src":"tension_9_source"
    },
    {   
        "id":"L_T_10",
        "condition":"Adaptive",
        "number":10,
        "src":"tension_10_source"
    }
]
var generative_videos_valence = [
    {   
        "id":"L_V_1",
        "condition":"Generative",
        "number":1,
        "src":"valence_1_source"
    },
    {   
        "id":"L_V_2",
        "condition":"Generative",
        "number":2,
        "src":"valence_2_source"
    },
    {   
        "id":"L_V_3",
        "condition":"Generative",
        "number":3,
        "src":"valence_3_source"
    },
    {   
        "id":"L_V_4",
        "condition":"Generative",
        "number":4,
        "src":"valence_4_source"
    },    
    {   
        "id":"L_V_5",
        "condition":"Generative",
        "number":5,
        "src":"valence_5_source"
    },
    {   
        "id":"L_V_6",
        "condition":"Generative",
        "number":6,
        "src":"valence_6_source"
    },
    {   
        "id":"L_V_7",
        "condition":"Generative",
        "number":7,
        "src":"valence_7_source"
    },
    {   
        "id":"L_V_8",
        "condition":"Generative",
        "number":8,
        "src":"valence_8_source"
    },
    {   
        "id":"L_V_9",
        "condition":"Generative",
        "number":9,
        "src":"valence_9_source"
    },
    {   
        "id":"L_V_10",
        "condition":"Generative",
        "number":10,
        "src":"valence_10_source"
    }]
    var generative_videos_arousal=[   
    {   
        "id":"L_A_1",
        "condition":"Generative",
        "number":1,
        "src":"arousal_1_source"
    },
    {   
        "id":"L_A_2",
        "condition":"Generative",
        "number":2,
        "src":"arousal_2_source"
    },
    {   
        "id":"L_A_3",
        "condition":"Generative",
        "number":3,
        "src":"arousal_3_source"
    },
    {   
        "id":"L_A_4",
        "condition":"Generative",
        "number":4,
        "src":"arousal_4_source"
    },    
    {   
        "id":"L_A_5",
        "condition":"Generative",
        "number":5,
        "src":"arousal_5_source"
    },
    {   
        "id":"L_A_6",
        "condition":"Generative",
        "number":6,
        "src":"arousal_6_source"
    },
    {   
        "id":"L_A_7",
        "condition":"Generative",
        "number":7,
        "src":"arousal_7_source"
    },
    {   
        "id":"L_A_8",
        "condition":"Generative",
        "number":8,
        "src":"arousal_8_source"
    },
    {   
        "id":"L_A_9",
        "condition":"Generative",
        "number":9,
        "src":"arousal_9_source"
    },
    {   
        "id":"L_A_10",
        "condition":"Generative",
        "number":10,
        "src":"arousal_10_source"
    }
]
var generative_videos_tension=[
    {   
        "id":"L_T_1",
        "condition":"Generative",
        "number":1,
        "src":"tension_1_source"
    },
    {   
        "id":"L_T_2",
        "condition":"Generative",
        "number":2,
        "src":"tension_2_source"
    },
    {   
        "id":"L_T_3",
        "condition":"Generative",
        "number":3,
        "src":"tension_3_source"
    },
    {   
        "id":"L_T_4",
        "condition":"Generative",
        "number":4,
        "src":"tension_4_source"
    },    
    {   
        "id":"L_T_5",
        "condition":"Generative",
        "number":5,
        "src":"tension_5_source"
    },
    {   
        "id":"L_T_6",
        "condition":"Generative",
        "number":6,
        "src":"tension_6_source"
    },
    {   
        "id":"L_T_7",
        "condition":"Generative",
        "number":7,
        "src":"tension_7_source"
    },
    {   
        "id":"L_T_8",
        "condition":"Generative",
        "number":8,
        "src":"tension_8_source"
    },
    {   
        "id":"L_T_9",
        "condition":"Generative",
        "number":9,
        "src":"tension_9_source"
    },
    {   
        "id":"L_T_10",
        "condition":"Generative",
        "number":10,
        "src":"tension_10_source"
    }
]


